[project]
name = "kafka-streamstore"
version = "0.1.0"
description = "Real-time order streaming with Kafka producers and consumers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["confluent-kafka"]
authors = [
    {name = "Rishi", email = "rishirochan@gmail.com"}
]